---
swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API Typescript'
  contact: {}
host: localhost:7000
basePath: /
tags:
  - name: 'Auth'
    description: ''
  - name: 'Reservas'
    description: ''
schemes:
  - 'https'
  - 'http'
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /auth/login:
    post:
      tags:
        - 'Auth'
      summary: 'Gera token'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'Body'
          required: true
          schema:
            $ref: '#/definitions/auth'
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/successResponseAuth'
        '401':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/errorResponse'
      deprecated: false

  
  /user/reservas:
      get:
        tags:
          - 'Reservas'
        summary: 'Get Reservas'
        produces:
          - 'application/json'
        parameters:
          # - name: Authorization
          #   in: header
          #   description: Token Bearer
          #   required: true
          #   type: string
          - name: 'empresa'
            in: header
            description: Empresa
            type: 'string'
            required: true
        responses:
          '200':
            description: ''
            headers: {}
            schema:
              $ref: '#/definitions/getReserva'
          '400':
            description: 'Bad Request'
            schema:
              $ref: '#/definitions/errorResponse'
        deprecated: false
        
definitions:
  errorResponse:
    type: object
    properties:
      message:
        type: string

  successResponseAuth:
    type: 'object'
    properties:
      token:
        type: 'string'

  auth:
    properties:
      username:
        type: 'string'
      password:
        type: 'string'

  getReserva:
    type: 'object'
    properties:
      Sucesso:
        type: 'boolean'
      Erros:
        type: 'array'
        items: 
          type: 'string'
      Data:
        type: 'array'
        items:
          $ref: '#/definitions/reserva'

  reserva:
    type: 'object'
    properties:
      CodigoReserva:
        type: 'number'
      CodigoEmpresa:
        type: 'number'
      CodigoUnidade:
        type: 'number'
      CodigoCliente:
        type: 'number'
      CodigoGrupoVeiculos:
        type: 'number'
      CodigoProtecao:
        type: 'number'
      CodigoTarifaVeiculo:
        type: 'number'
      DataHoraInicio:
        type: 'string'
      DataHoraTermino:
        type: 'string'
      DataInicio:
        type: 'string'
      HoraInicio:
        type: 'string'
      DataTermino:
        type: 'string'
      HoraTermino:
        type: 'string'
      CodigoLocalRetirada:
        type: 'number'
      LocalEntregaCodigoMunicipio:
        type: 'number'
      LocalDevolucaoCodigoMunicipio:
        type: 'number'
      Origem:
        type: 'string'
      CPF:
        type: 'string'
      CNPJ:
        type: 'string'