# version: '3.1'

# services:
#   mysql_knex:
#     container_name: mysql_knex
#     hostname: mysql_knex
#     image: mysql
#     restart: always
#     command:
#       - --default-authentication-plugin=mysql_native_password
#       - --character-set-server=utf8mb4
#       - --collation-server=utf8mb4_unicode_ci
#       - --innodb_force_recovery=0
#     volumes: 
#       - ~/.Desktop/meus projetos/mysql:/var/lib/mysql
#     ports:
#       - 1433:1433
#     environment:
#       MYSQL_ROOT_PASSWORD: senha
#       MYSQL_DATABASE: Banco_de_Dados
#       MYSQL_USER: sa
#       MYSQL_PASSWORD: 1q2w3e4r@#$
#       TZ: America/Sao_Paulo
docker run -v ~/docker --name sqlserver -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=1q2w3e4r@#$" -p 1433:1433 -d mcr.microsoft.com/mssql/server