---
swagger: '2.0'
info:
  version: '1.0.0'
  title: 'API Typescript'
  contact: {}
host: localhost:7000
basePath: /
tags:
  - name: 'Auth'
    description: ''
  - name: 'User'
    description: ''
schemes:
  - 'https'
  - 'http'
consumes:
  - 'application/json'
produces:
  - 'application/json'
paths:
  /auth/login:
    post:
      tags:
        - 'Auth'
      summary: 'Gera token'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'Body'
          required: true
          schema:
            $ref: '#/definitions/auth'
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/successResponseAuth'
        '401':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/errorResponse'
      deprecated: false

  /user:
    get:
      tags:
        - 'User'
      summary: 'Get User'
      produces:
        - 'application/json'
      parameters:
        # - name: Authorization
        #   in: header
        #   description: Token Bearer
        #   required: true
        #   type: string
        - name: 'empresa'
          in: header
          description: Empresa
          type: 'string'
          required: true
      responses:
        '200':
          description: ''
          headers: {}
          schema:
            $ref: '#/definitions/getUser'
        '400':
          description: 'Bad Request'
          schema:
            $ref: '#/definitions/errorResponse'
      deprecated: false

definitions:
  errorResponse:
    type: object
    properties:
      message:
        type: string

  successResponseAuth:
    type: 'object'
    properties:
      token:
        type: 'string'

  auth:
    properties:
      username:
        type: 'string'
      password:
        type: 'string'

  getUser:
    type: 'object'
    properties:
      data:
        type: 'array'
        items:
          $ref: '#/definitions/user'

  user:
    type: 'object'
    properties:
      userID:
        type: 'number'
      name:
        type: 'string'
      email:
        type: 'string'
      username:
        type: 'string'
      password:
        type: 'string'
